#
# Copyright 2018 Freescale Semiconductor
# Copyright 2022-2023 NXP
# SPDX-License-Identifier:	GPL-2.0+
#

obj-y += lx2160a.o
obj-y += ddr.o
obj-$(CONFIG_TARGET_LX2160ARDB) += eth_lx2160ardb.o
obj-$(CONFIG_TARGET_LX2160AQDS) += eth_lx2160aqds.o
obj-$(CONFIG_TARGET_LX2162AQDS) += eth_lx2162aqds.o
obj-$(CONFIG_TARGET_LA1238RDB) += eth_la1238rdb.o
obj-$(CONFIG_TARGET_LA1224RDB) += eth_la1224rdb.o
