#
# Copyright 2018 NXP
# SPDX-License-Identifier:	GPL-2.0+        BSD-3-Clause
#
# Author York Sun <york.sun@nxp.com>
#

obj-y += main.o phy_gen2_init.o phy_gen2_phy_io.o
obj-y += g_execfw.o h_readmsgblock.o i_loadpie.o
obj-y += phy_gen2_fit.o phy_gen2_xip.o
